### ISSUE TITLE
Disembarking with holo pilot crashes the client

### ISSUE THREAD

**Issue by L1ghtman2k** [Legonzaur/Legonzaur.HoloShift#1]
I following error when disembarking with the holo pilot:
![image](https://user-images.githubusercontent.com/35672535/152661284-8006e370-42bf-4f0a-a6eb-34dd1108aaf0.png)

log file: [nslog2022-02-05 17-34-16.txt](https://github.com/Legonzaur/Legonzaur.HoloShift/files/8009044/nslog2022-02-05.17-34-16.txt)

Servers have the copy of the file, and I am using Linux containers: https://github.com/pg9182/northstar-dedicated (though this might not be relevant)

**Comment by Legonzaur** [comment]
To clarify the issue, was the mod installed on your client ?

**Comment by L1ghtman2k** [comment]
Yes, both the server and client

**Comment by Legonzaur** [comment]
I understand, I'll look into this

As a workaround don't install the mod on client until this is fixed

**Comment by Legonzaur** [comment]
fixed in 37be9bc2c60338d27c7343e9cb6768cef01fb348
